### ISSUE TITLE
Peers do not see accurate locations of other peers on initial connect

### ISSUE THREAD

**Issue by tttaaannnggg** [together-support/togethernet#10]
If peer A connects and moves, then peer B connects, peer A's location will not be accurately represented on peer B's DOM. should probably broadcast initial location on connect, or centralize information on the server

**Comment by ywenc** [comment]
This issue has been fixed as of https://github.com/together-support/togethernet/commit/3d72ba59073efd6f9a03b03aa3de58a71ac9d71f#diff-31f84809ed40579208aa0f03d431df2ea57b64440bf823e9245755135f79d8d1
