### ISSUE TITLE
UI position issues with >2 peer connections + no visual for disconnects

### ISSUE THREAD

**Issue by tttaaannnggg** [together-support/togethernet#9]
* colored squares do not accurately reflect peer positions if more than 2 peers are connected
* colored squares are not removed from DOM on peer disconnect

we should probably refactor the `peers` object to hold a reference to the DOM node, the simplepeer connection, and possibly the coordinates/state of each peer, making it easier for us to correctly remove the square upon detecting a peer disconnect.

**Comment by ywenc** [comment]
this has been resolved as of https://github.com/together-support/togethernet/commit/3d72ba59073efd6f9a03b03aa3de58a71ac9d71f#diff-31f84809ed40579208aa0f03d431df2ea57b64440bf823e9245755135f79d8d1
